repository_type: pipeline

nf_core_version: 3.5.1

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-fingerprinter_logo_light.png
    - docs/images/nf-core-fingerprinter_logo_light.png
    - docs/images/nf-core-fingerprinter_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-fingerprinter_logo_light.png
    - docs/images/nf-core-fingerprinter_logo_light.png
    - docs/images/nf-core-fingerprinter_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: anoronh4
  name: fingerprinter
  description: Standalone workflow for fingerprinting samples, taking in fingerprint
    files or bam files
  author: Anne Marie Noronha
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - gpu
  is_nfcore: false
