# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "custom_fingerprintcontamination"
description: "Calculate major and minor contamination from fingerprint tables"
version: "0.1.0"
keywords:
  - fingerprint
  - contamination
  - qc
tools:
  - "pandas":
      description: "Python Data Analysis Library"
      homepage: "https://pandas.pydata.org/"
      documentation: "https://pandas.pydata.org/docs/"
      identifier: biotools:pandas
  - "numpy":
      description: "Scientific computing library for Python"
      homepage: "https://numpy.org/"
      documentation: "https://numpy.org/doc/"

      identifier: biotools:numpy
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - fp_tumor:
        type: file
        description: Fingerprint table file for tumor sample
        pattern: "*.fp.tsv"
        ontologies:
          - edam: "http://edamontology.org/format_3750" # TSV
          - edam: http://edamontology.org/format_3475 # TSV
    - fp_normal:
        type: file
        description: Fingerprint table file for normal sample
        pattern: "*.fp.tsv"
        ontologies:
          - edam: "http://edamontology.org/format_3750"

          - edam: http://edamontology.org/format_3475 # TSV
output:
  contamination_tsv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.contamination.tsv":
          type: file
          description: Contamination results table
          pattern: "*.contamination.tsv"
          ontologies:
            - edam: "http://edamontology.org/format_3750" # TSV
            - edam: http://edamontology.org/format_3475 # TSV
  versions_fingerprintvcfparser:
    - - ${task.process}: {}
      - calculate_contamination.py: {}
      - 'calculate_contamination.py -v | cut -f 2 -d" ': {}
authors:
  - "@anoronh4"
maintainers:
  - "@anoronh4"
